language: python
python:
  - 3.6
  - 3.7

sudo: false

env:
    - TEST_DIR="tests"

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda env create -f environment.yml
  - conda activate em-notebooks-environment
  - pip install -r dev-requirements.txt
  - export MPLBACKEND="agg"

# Run test
script:
  - travis_wait 40 pytest $TEST_DIR -v

